### This jupyter notebook contains contents of the lesson "Loading and editing different types of datasets"

**Author : Umidjon Sattorov. Machine Learning engineer**

In [1]:
import pandas as pd

## Fayllarni o'qish

`pandas` kutubxonasi fayllar bilan ishlaydigan bir nechta funksiyalardan iborat.

`read_csv` - vergul bilan ajratilgan jadval fayllarni o'qish uchun

`read_table` - probel (bo'sh joy) bilan ajratilgan jadval fayllarni o'qish uchun

`read_excel` - `xls` yoki `xlsx` formatidagi **Excel** fayllarni o'qish uchun

`read_clipboard` - ko'chirilgan (xotiradagi) jadvalni o'qish

`read_hdf` - `HDF5` formatidagi fayllarni o'qish

`read_html` - HTML (web) sahifadagi barcha jadvallarni o'qish

`read_json` - `JSON` ma'lumotlarni o'qish

`read_pickle` - pickle formatidagi fayllarni o'qish

`read_sql` - SQL query dan qaytgan ma'lumotlarni o'qish (SQLAlchemy bilan ishlayd)

Yuqoridagi funksiyalarning deyarlari barchasining ishlashi juda o'xshash, muhimi, to'g'ri formatdagi faylni ko'rsatish va turli qo'shimcha parametrlardan foydalangan xolda jadvalni to'g'ri yaratib olish.

### Fayllardan o'qib olish

In [ ]:
%pip install openpyxl

In [7]:
# Loading netflix dataset from xlsx file
netflix = pd.read_excel('./netflix.xlsx')
netflix.head(10)

,title,rating,ratingLevel,ratingDescription,release year,user rating score,user rating size
0,White Chicks,PG-13,"crude and sexual humor, language and some drug...",80,2004,82.0,80
1,Lucky Number Slevin,R,"strong violence, sexual content and adult lang...",100,2006,NaN,82
2,Grey's Anatomy,TV-14,Parents strongly cautioned. May be unsuitable ...,90,2016,98.0,80
3,Prison Break,TV-14,Parents strongly cautioned. May be unsuitable ...,90,2008,98.0,80
4,How I Met Your Mother,TV-PG,Parental guidance suggested. May not be suitab...,70,2014,94.0,80
5,Supernatural,TV-14,Parents strongly cautioned. May be unsuitable ...,90,2016,95.0,80
6,Breaking Bad,TV-MA,For mature audiences. May not be suitable for...,110,2013,97.0,80
7,The Vampire Diaries,TV-14,Parents strongly cautioned. May be unsuitable ...,90,2017,91.0,80
8,The Walking Dead,TV-MA,For mature audiences. May not be suitable for...,110,2015,98.0,80
9,Pretty Little Liars,TV-14,Parents strongly cautioned. May be unsuitable ...,90,2016,96.0,80

In [9]:
# Column name and index
netflix_1 = pd.read_excel('./netflix.xlsx', names = ["sarlavha", "reyting", "reyting_darajasi", "reyting_tavsifi", "chiqarilgan_yili", "foydalanuvchi_reyting_bahosi", "foydalanuvchi_reyting_soni"], index_col = 0)
netflix_1

,reyting,reyting_darajasi,reyting_tavsifi,chiqarilgan_yili,foydalanuvchi_reyting_bahosi,foydalanuvchi_reyting_soni
sarlavha,,,,,,
White Chicks,PG-13,"crude and sexual humor, language and some drug...",80,2004,82.0,80
Lucky Number Slevin,R,"strong violence, sexual content and adult lang...",100,2006,NaN,82
Grey's Anatomy,TV-14,Parents strongly cautioned. May be unsuitable ...,90,2016,98.0,80
Prison Break,TV-14,Parents strongly cautioned. May be unsuitable ...,90,2008,98.0,80
How I Met Your Mother,TV-PG,Parental guidance suggested. May not be suitab...,70,2014,94.0,80
...,...,...,...,...,...,...
The BFG,PG,"for action/peril, some scary moments and brief...",60,2016,97.0,80
The Secret Life of Pets,PG,for action and some rude humor,60,2016,NaN,81
Precious Puppies,TV-G,Suitable for all ages.,35,2003,NaN,82
Beary Tales,TV-G,Suitable for all ages.,35,2013,NaN,82
Growing Up Wild,G,NaN,35,2016,80.0,80

In [11]:
# Loading from the internet
cv19 = pd.read_json('https://opendata.ecdc.europa.eu/covid19/casedistribution/json/', encoding = "UTF-8")
cv19

                                                 records
0      {'dateRep': '14/12/2020', 'day': '14', 'month'...
1      {'dateRep': '13/12/2020', 'day': '13', 'month'...
2      {'dateRep': '12/12/2020', 'day': '12', 'month'...
3      {'dateRep': '11/12/2020', 'day': '11', 'month'...
4      {'dateRep': '10/12/2020', 'day': '10', 'month'...
...                                                  ...
61895  {'dateRep': '25/03/2020', 'day': '25', 'month'...
61896  {'dateRep': '24/03/2020', 'day': '24', 'month'...
61897  {'dateRep': '23/03/2020', 'day': '23', 'month'...
61898  {'dateRep': '22/03/2020', 'day': '22', 'month'...
61899  {'dateRep': '21/03/2020', 'day': '21', 'month'...

[61900 rows x 1 columns]

In [13]:
# Normalize json
cv19 = pd.json_normalize(data = cv19['records'])
cv19.head()

KeyError: 'records'

In [16]:
# Checking if there is any missing data
cv19.isna().sum()

dateRep                                                         0
day                                                             0
month                                                           0
year                                                            0
cases                                                           0
deaths                                                          0
countriesAndTerritories                                         0
geoId                                                           0
countryterritoryCode                                          123
popData2019                                                   123
continentExp                                                    0
Cumulative_number_for_14_days_of_COVID-19_cases_per_100000      0
dtype: int64

In [17]:
cv19.tail()

,dateRep,day,month,year,cases,deaths,countriesAndTerritories,geoId,countryterritoryCode,popData2019,continentExp,Cumulative_number_for_14_days_of_COVID-19_cases_per_100000
61895,25/03/2020,25,03,2020,0,0,Zimbabwe,ZW,ZWE,14645473.0,Africa,
61896,24/03/2020,24,03,2020,0,1,Zimbabwe,ZW,ZWE,14645473.0,Africa,
61897,23/03/2020,23,03,2020,0,0,Zimbabwe,ZW,ZWE,14645473.0,Africa,
61898,22/03/2020,22,03,2020,1,0,Zimbabwe,ZW,ZWE,14645473.0,Africa,
61899,21/03/2020,21,03,2020,1,0,Zimbabwe,ZW,ZWE,14645473.0,Africa,

In [18]:
# CSV
diabetes = pd.read_csv('https://raw.githubusercontent.com/datasets/diagnosed-diabetes-prevalence/refs/heads/main/data.csv', sep = ',', nrows = 1000)
diabetes

,State,FIPS_Code,County,Year,Number,Percent,Lower_Confidence_Limit,Upper_Confidence_Limit,Age_Adjusted_Percent,Age_Adjusted_Lower_Confidence_Limit,Age_Adjusted_Upper_Confidence_Limit
0,Alabama,1001,Autauga County,2004,3368,10.0,7.8,12.8,9.9,7.8,12.6
1,Alabama,1003,Baldwin County,2004,9509,8.1,6.5,9.9,7.2,5.7,9.0
2,Alabama,1005,Barbour County,2004,2117,10.1,7.9,12.8,9.7,7.7,12.2
3,Alabama,1007,Bibb County,2004,1406,8.9,6.9,11.5,9.0,6.9,11.8
4,Alabama,1009,Blount County,2004,3367,8.3,6.3,10.8,8.0,6.1,10.4
...,...,...,...,...,...,...,...,...,...,...,...
995,Kentucky,21071,Floyd County,2004,3326,10.5,8.3,13.1,10.0,7.9,12.5
996,Kentucky,21073,Franklin County,2004,3103,8.6,6.6,11.0,8.2,6.3,10.5
997,Kentucky,21075,Fulton County,2004,573,10.5,8.0,13.5,9.2,6.9,12.0
998,Kentucky,21077,Gallatin County,2004,493,8.8,6.4,11.8,8.6,6.3,11.5
999,Kentucky,21079,Garrard County,2004,1040,8.6,6.4,11.3,8.3,6.2,11.0

___

### Fayllarga yozish

In [19]:
# Writing to csv format
diabetes.to_csv('./Ibrat_ds.csv', sep = '|')
print("Saved successfully")

Saved successfully

In [ ]:
# Check df
check_df = pd.read_csv('./Ibrat_ds.csv', sep = '|', index_col = 0) # index_col
check_df

,State,FIPS_Code,County,Year,Number,Percent,Lower_Confidence_Limit,Upper_Confidence_Limit,Age_Adjusted_Percent,Age_Adjusted_Lower_Confidence_Limit,Age_Adjusted_Upper_Confidence_Limit
0,Alabama,1001,Autauga County,2004,3368,10.0,7.8,12.8,9.9,7.8,12.6
1,Alabama,1003,Baldwin County,2004,9509,8.1,6.5,9.9,7.2,5.7,9.0
2,Alabama,1005,Barbour County,2004,2117,10.1,7.9,12.8,9.7,7.7,12.2
3,Alabama,1007,Bibb County,2004,1406,8.9,6.9,11.5,9.0,6.9,11.8
4,Alabama,1009,Blount County,2004,3367,8.3,6.3,10.8,8.0,6.1,10.4
...,...,...,...,...,...,...,...,...,...,...,...
995,Kentucky,21071,Floyd County,2004,3326,10.5,8.3,13.1,10.0,7.9,12.5
996,Kentucky,21073,Franklin County,2004,3103,8.6,6.6,11.0,8.2,6.3,10.5
997,Kentucky,21075,Fulton County,2004,573,10.5,8.0,13.5,9.2,6.9,12.0
998,Kentucky,21077,Gallatin County,2004,493,8.8,6.4,11.8,8.6,6.3,11.5
999,Kentucky,21079,Garrard County,2004,1040,8.6,6.4,11.3,8.3,6.2,11.0

In [37]:
# Saving to excel
diabetes.to_excel('diabetes.xlsx', index = False)

## HDF5 formati


HDF5 formati ilmiy tadqiqodlar qilishda katta hajmdagi ma'lumotlarni saqlash uchun keng ioshlatiladigan formatlardan hisoblanadi. 

HDF5 fayllarni nafaqat Python, balki Java, Julia, Matlab va boshqa dasturlash tillarida ochish mumkin. 

HDF - __hierarchial data format__ (irarxiyali ma'lumotlar formati) hisoblanib, tarkibida bir nechta datasetlarni siqilgan holatda saqlashi mumkin.

HDF formatida fayllarni saqlash uchun avval HDF obyketini yaratamiz:

In [ ]:
%pip install tables

In [37]:
# Creating hdf object
hdfobj = pd.HDFStore("movie_med.h5")

In [38]:
# Saving dataframes
hdfobj['netflix'] = netflix
hdfobj['diabetes'] = diabetes

C:\Users\User\AppData\Local\Temp\ipykernel_13624\3180980231.py:2: PerformanceWarning:
your performance may suffer as PyTables will pickle object types that it cannot
map directly to c-types [inferred_type->mixed-integer,key->block2_values] [items->Index(['title', 'rating', 'ratingLevel'], dtype='object')]

  hdfobj['netflix'] = netflix

In [41]:
hdfobj['netflix']

,title,rating,ratingLevel,ratingDescription,release year,user rating score,user rating size
0,White Chicks,PG-13,"crude and sexual humor, language and some drug...",80,2004,82.0,80
1,Lucky Number Slevin,R,"strong violence, sexual content and adult lang...",100,2006,NaN,82
2,Grey's Anatomy,TV-14,Parents strongly cautioned. May be unsuitable ...,90,2016,98.0,80
3,Prison Break,TV-14,Parents strongly cautioned. May be unsuitable ...,90,2008,98.0,80
4,How I Met Your Mother,TV-PG,Parental guidance suggested. May not be suitab...,70,2014,94.0,80
...,...,...,...,...,...,...,...
995,The BFG,PG,"for action/peril, some scary moments and brief...",60,2016,97.0,80
996,The Secret Life of Pets,PG,for action and some rude humor,60,2016,NaN,81
997,Precious Puppies,TV-G,Suitable for all ages.,35,2003,NaN,82
998,Beary Tales,TV-G,Suitable for all ages.,35,2013,NaN,82
999,Growing Up Wild,G,NaN,35,2016,80.0,80

In [45]:
hdfobj.keys()

ClosedFileError: movie_med.h5 file is not open!

In [43]:
hdfobj.close()

In [44]:
hdfobj

<class 'pandas.io.pytables.HDFStore'>
File path: movie_med.h5

In [46]:
# to_hdf()
netflix.to_hdf('net.h5', key = 'net')

C:\Users\User\AppData\Local\Temp\ipykernel_13624\1920647947.py:2: PerformanceWarning:
your performance may suffer as PyTables will pickle object types that it cannot
map directly to c-types [inferred_type->mixed-integer,key->block2_values] [items->Index(['title', 'rating', 'ratingLevel'], dtype='object')]

  netflix.to_hdf('net.h5', key = 'net')

In [ ]:
# Reading from hdf
df = pd.read_hdf('net.h5', key = 'net')
df.head()

,title,rating,ratingLevel,ratingDescription,release year,user rating score,user rating size
0,White Chicks,PG-13,"crude and sexual humor, language and some drug...",80,2004,82.0,80
1,Lucky Number Slevin,R,"strong violence, sexual content and adult lang...",100,2006,NaN,82
2,Grey's Anatomy,TV-14,Parents strongly cautioned. May be unsuitable ...,90,2016,98.0,80
3,Prison Break,TV-14,Parents strongly cautioned. May be unsuitable ...,90,2008,98.0,80
4,How I Met Your Mother,TV-PG,Parental guidance suggested. May not be suitab...,70,2014,94.0,80